# vim:ft=kitty

# ── General ──────────────────────────────────────────────
hide_window_decorations yes
confirm_os_window_close 0
enable_audio_bell no
scrollback_lines 10000

# ── Fuente ───────────────────────────────────────────────
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# ── Cursor ───────────────────────────────────────────────
cursor_shape beam
cursor_blink_interval 0

# ── Tabs ─────────────────────────────────────────────────
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index}: {title}"

# ── Shortcuts ────────────────────────────────────────────
# ── Tabs ─────────────────────────────────────────────────
map ctrl+alt+t     new_tab_with_cwd
map ctrl+alt+w     close_tab
map ctrl+alt+right next_tab
map ctrl+alt+left  previous_tab

# ── Splits ───────────────────────────────────────────────
map ctrl+alt+l launch --location=vsplit --cwd=current
map ctrl+alt+j launch --location=hsplit --cwd=current
map ctrl+alt+h neighboring_window left
map ctrl+alt+k neighboring_window up
map ctrl+alt+n neighboring_window down
map ctrl+alt+i neighboring_window right

# ── Fuente ───────────────────────────────────────────────
map ctrl+equal change_font_size all +1.# ── Colores (Base2Tone Mall Dark) ────────────────────────
foreground              #97959d
background              #1e1e1f
selection_foreground    #97959d
selection_background    #2b2b2c
cursor                  #3692e2
cursor_text_color       #1e1e1f
url_color               #e5dbff
active_border_color     #515053
inactive_border_color   #1e1e1f
bell_border_color       #855ee8
wayland_titlebar_color  #2b2b2c
active_tab_foreground   #f8fafc
active_tab_background   #1e1e1f
inactive_tab_foreground #a2abb3
inactive_tab_background #2b2b2c
tab_bar_background      #2b2b2c
mark1_foreground #1e1e1f
mark1_background #936df3
mark2_foreground #1e1e1f
mark2_background #7e8891
mark3_foreground #1e1e1f
mark3_background #479eeb
color0  #1e1e1f
color8  #5e5c60
color1  #a17efc
color9  #8ac8ff
color2  #75bfff
color10 #2b2b2c
color3  #b3dbff
color11 #515053
color4  #b294ff
color12 #6a686e
color5  #75bfff
color13 #e5dbff
color6  #c5adff
color14 #69b5f7
color7  #97959d
color15 #f4f0ff
